version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=aneural
      - POSTGRES_PASSWORD=aneural
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - ./wait-for-postgres.sh:/wait-for-postgres.sh
    command: sh -c './wait-for-postgres.sh db python simple.py'
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 8000:8000
